// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcOQbihOhAhXjhilo_u9o-4bwSYmZIuwg',
    appId: '1:967719220804:web:d28e0669e2854e13db2e11',
    messagingSenderId: '967719220804',
    projectId: 'fairsplit-91ade',
    authDomain: 'fairsplit-91ade.firebaseapp.com',
    storageBucket: 'fairsplit-91ade.firebasestorage.app',
    measurementId: 'G-MFL5YGW384',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpebtgkiXH6gTRxkVWoLgouVKFOm5Iw4c',
    appId: '1:967719220804:android:db039a363ff84884db2e11',
    messagingSenderId: '967719220804',
    projectId: 'fairsplit-91ade',
    storageBucket: 'fairsplit-91ade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI5bK_AWvGv317BIHTmLuxXmE4Wa9q_4M',
    appId: '1:967719220804:ios:bdeff19128ff47f2db2e11',
    messagingSenderId: '967719220804',
    projectId: 'fairsplit-91ade',
    storageBucket: 'fairsplit-91ade.firebasestorage.app',
    iosClientId:
        '967719220804-35p45ahsplqqal8nkbdfeldvsuqq76os.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI5bK_AWvGv317BIHTmLuxXmE4Wa9q_4M',
    appId: '1:967719220804:ios:739d64029f1c8429db2e11',
    messagingSenderId: '967719220804',
    projectId: 'fairsplit-91ade',
    storageBucket: 'fairsplit-91ade.firebasestorage.app',
    iosClientId:
        '967719220804-nq9tdbbq48h13gngg415hufcn9qceimn.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcOQbihOhAhXjhilo_u9o-4bwSYmZIuwg',
    appId: '1:967719220804:web:59b80bf7a07a4c45db2e11',
    messagingSenderId: '967719220804',
    projectId: 'fairsplit-91ade',
    authDomain: 'fairsplit-91ade.firebaseapp.com',
    storageBucket: 'fairsplit-91ade.firebasestorage.app',
    measurementId: 'G-29XEHXGW9R',
  );
}
